### ISSUE TITLE
(TKSprites) GL.Uniform1 binding to non-existent attribute.

### ISSUE THREAD

**Issue by ghost** [neokabuto/OpenTKTutorialContent#5]
"mytexture" is a uniform, not an attribute. So when you Uniform1 to GetAttribute("mytexture"), you're Uniform1'ing to -1.

Your GL.BindTexture(texture2d, texture id) is what makes the whole function work. If commented out, squares become black.

The other 'weird' thing about this is that if you uniform1 to the appropriate variable, which is 1 (GetUniform("mytexture") returns 1), the squares will also become black, ignoring the GL.BindTexture.

**Comment by neokabuto** [comment]
Thanks for catching this. There's a more subtle mistake here too: having the uniform sending the texture ID instead of the texture unit number (zero in this case, so it was defaulting to the correct value). When the uniform was actually being set properly, it told it to load a texture that hadn't been set, making everything black. 

It's fixed in 49d3b844c706653e7c6bb5c3478d36d3cdb2ab48.
